(function(){'use strict';
const API='https://bodibedigital-backend.onrender.com',details=document.getElementById('paymentDetails'),status=document.getElementById('paymentStatus'),actions=document.getElementById('paymentActions'),pay=document.getElementById('payYoco'),refresh=document.getElementById('refreshPayment');
const params=new URLSearchParams(location.hash.slice(1)),token=params.get('token')||sessionStorage.getItem('bodibe.invoiceAccess'),paymentId=params.get('payment')||sessionStorage.getItem('bodibe.paymentId');
if(params.has('token')){sessionStorage.setItem('bodibe.invoiceAccess',token);sessionStorage.removeItem('bodibe.paymentId');}
const money=n=>new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format(n),text=(tag,value)=>{const n=document.createElement(tag);n.textContent=value;return n;};
async function request(path,body={}){const r=await fetch(API+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,...body})});let b;try{b=await r.json();}catch{throw Error('Payment service is unavailable. Please contact Bodibe before paying again.');}if(!r.ok||!b.success)throw Error(b.message||'Unable to check payment.');return b;}
async function load(){refresh.disabled=true;try{
 if(!token)throw Error('Open the official payment link supplied with your invoice.');
 const b=await request('/payments/yoco/invoice'),i=b.invoice;details.replaceChildren(text('h2',i.invoiceId),text('p',i.clientName));const dl=document.createElement('dl');for(const [label,value]of [['Invoice total',i.total],['Confirmed paid',i.amountPaid],['Outstanding',i.balanceDue]])dl.append(text('dt',label),text('dd',money(value)));details.append(dl);
 document.getElementById('paymentMode').textContent=b.mode==='test'?'TEST CHECKOUT — no real payment, revenue or payable commission.':'';
 document.getElementById('eftInstructions').textContent=b.eftInstructions;actions.hidden=i.balanceDue<=0;document.getElementById('paymentPartLabel').hidden=!(i.depositOutstanding>=2&&i.depositOutstanding<i.balanceDue);document.querySelector('#paymentPart option[value=deposit]').textContent='Required deposit · '+money(i.depositOutstanding);
 const current=params.has('token')?null:paymentId;
 if(current){const p=await request('/payments/yoco/status',{paymentId:current});if(p.status==='Paid'){status.textContent='Payment received. Thank you.';actions.hidden=true;}else if(p.status==='Test Paid'){status.textContent='Test payment confirmed. Your real invoice and business records have not changed.';actions.hidden=true;}else if(p.status==='Failed'){status.textContent='Payment unsuccessful. You may try again for this invoice or use EFT.';}else{status.textContent=p.status==='Review Required'?'Payment requires Finance review. Please do not pay again.':'Your payment is being confirmed. Please do not make another payment.';actions.hidden=true;}}
 }catch(e){status.textContent=e.message;actions.hidden=true;}finally{details.removeAttribute('aria-busy');refresh.disabled=false;}}
pay.onclick=async()=>{pay.disabled=true;status.textContent='Preparing secure checkout…';try{const b=await request('/payments/yoco/checkout',{part:document.getElementById('paymentPart').value});const u=new URL(b.checkoutUrl);if(u.protocol!=='https:'||!['c.yoco.com','payments.yoco.com'].includes(u.hostname)||u.username||u.password)throw Error('Checkout link could not be verified. Contact Bodibe.');sessionStorage.setItem('bodibe.paymentId',b.paymentId);location.assign(u.href);}catch(e){status.textContent=e.message;pay.disabled=false;}};
refresh.onclick=load;load();
})();
