/* Bodibe Digital — Staff Profile */
(function(window,document){'use strict';var Portal=window.BodibePortal;if(!Portal)return;var state={profile:null,editable:[],owner:false,pendingPhoto:'',target:'me',directory:[]};var dialog=document.getElementById('profileDialog');
function esc(v){return Portal.escapeHtml(v==null?'':v)}function value(v){return String(v||'').trim()||'—'}
async function json(path,options){var res=await Portal.authedFetch(path,options||{});var data=await res.json().catch(function(){return{}});if(!res.ok||!data.success)throw new Error(data.message||'Profile request failed.');return data}
var groups={personal:[['firstName','First name'],['surname','Surname'],['dateOfBirth','Date of birth'],['gender','Gender'],['nationality','Nationality'],['idPassport','ID / passport']],employment:[['employmentDate','Employment date'],['employmentStatus','Employment status'],['employmentType','Employment type'],['manager','Manager'],['grade','Grade'],['workLocation','Work location'],['salaryRate','Salary / rate'],['taxNumber','Tax number']],contact:[['email','Contact email'],['phone','Phone'],['address','Address'],['emergencyName','Emergency contact'],['emergencyPhone','Emergency phone'],['emergencyRelationship','Relationship'],['bankName','Bank'],['accountNumber','Account number'],['branchCode','Branch code']],skills:[['skills','Skills'],['qualifications','Qualifications'],['notes','Notes']]};
function fieldHtml(pair,wide){var f=state.profile.fields||{},v=f[pair[0]];return '<div class="profile-field'+(wide?' is-wide':'')+'"><span>'+esc(pair[1])+'</span><strong>'+esc(value(v))+'</strong></div>'}
function renderGroup(id,name){var list=groups[name],wide=name==='skills';document.getElementById(id).innerHTML=list.map(function(x){return fieldHtml(x,wide)}).join('')}
function render(){var p=state.profile,f=p.fields||{};document.getElementById('profileStaffId').textContent=p.staffId||'—';document.getElementById('profileName').textContent=p.name||[f.firstName,f.surname].filter(Boolean).join(' ')||'—';document.getElementById('profileRole').textContent=p.role||'—';document.getElementById('profileStatus').textContent=p.status||'—';document.getElementById('profileDepartment').textContent=p.department||'—';document.getElementById('profileLogin').textContent=p.loginId||'—';var initials=(p.name||'').split(/\s+/).slice(0,2).map(function(x){return x[0]||''}).join('').toUpperCase()||'—';var photo=f.photoData||f.photoUrl||'';var box=document.getElementById('profilePhoto');box.innerHTML=photo?'<img alt="Profile photo" src="'+esc(photo)+'">':'<span id="profileInitials">'+esc(initials)+'</span>';renderGroup('personalFields','personal');renderGroup('employmentFields','employment');renderGroup('contactFields','contact');renderGroup('skillsFields','skills');var other=state.target!=='me';document.getElementById('profileHeaderTitle').textContent=other?'Staff profile':'My profile';document.getElementById('profileHeaderCopy').textContent=other?'Review and update this employee’s approved profile fields.':'Keep your personal details and staff information accurate.';document.getElementById('editProfileLabel').textContent=other?'Edit staff profile':'Edit profile';document.getElementById('profileDialogTitle').textContent=other?'Edit '+(p.name||'staff profile'):'Edit your profile'}
var labels={firstName:'First name',surname:'Surname',phone:'Phone',dateOfBirth:'Date of birth',gender:'Gender',email:'Contact email',address:'Address',emergencyName:'Emergency contact name',emergencyPhone:'Emergency phone',emergencyRelationship:'Emergency relationship',skills:'Skills',qualifications:'Qualifications',idPassport:'ID / passport',employmentDate:'Employment date',employmentStatus:'Employment status',manager:'Manager',employmentType:'Employment type',grade:'Grade',workLocation:'Work location',salaryRate:'Salary / rate',bankName:'Bank name',accountNumber:'Account number',branchCode:'Branch code',taxNumber:'Tax number',nationality:'Nationality',notes:'Notes'};
function inputType(f){return ['dateOfBirth','employmentDate'].includes(f)?'date':'text'}
function openEdit(){var fields=state.editable.filter(function(f){return f!=='photoData'&&f!=='photoUrl'});var f=state.profile.fields||{};var html='<div class="profile-photo-control"><label><span>Profile photo</span><input type="file" id="profilePhotoInput" accept="image/jpeg,image/png,image/webp"></label><small>JPEG, PNG or WebP. The image is resized before saving.</small></div>';html+=fields.map(function(name){var wide=['address','skills','qualifications','notes'].includes(name);var tag=wide?'textarea':'input';if(tag==='textarea')return '<label class="is-wide"><span>'+esc(labels[name]||name)+'</span><textarea data-profile-field="'+esc(name)+'" rows="3">'+esc(f[name]||'')+'</textarea></label>';return '<label><span>'+esc(labels[name]||name)+'</span><input data-profile-field="'+esc(name)+'" type="'+inputType(name)+'" value="'+esc(f[name]||'')+'"></label>'}).join('');document.getElementById('profileFormFields').innerHTML=html;state.pendingPhoto='';var photoInput=document.getElementById('profilePhotoInput');if(photoInput)photoInput.addEventListener('change',preparePhoto);dialog.showModal()}
function preparePhoto(e){var file=e.target.files&&e.target.files[0];if(!file)return;if(!/^image\/(jpeg|png|webp)$/.test(file.type)){Portal.showNotice('Choose a JPEG, PNG or WebP photo.','warning');e.target.value='';return}var reader=new FileReader();reader.onload=function(){var img=new Image();img.onload=function(){var c=document.createElement('canvas');c.width=192;c.height=192;var ctx=c.getContext('2d'),s=Math.min(img.width,img.height),sx=(img.width-s)/2,sy=(img.height-s)/2;ctx.drawImage(img,sx,sy,s,s,0,0,192,192);var data=c.toDataURL('image/jpeg',.72);if(data.length>90000){Portal.showNotice('That photo is still too large. Choose a smaller image.','warning');return}state.pendingPhoto=data};img.src=reader.result};reader.readAsDataURL(file)}
async function save(e){e.preventDefault();var payload={};document.querySelectorAll('[data-profile-field]').forEach(function(el){payload[el.dataset.profileField]=el.value.trim()});if(state.pendingPhoto&&state.editable.includes('photoData'))payload.photoData=state.pendingPhoto;var button=document.getElementById('saveProfile');button.disabled=true;try{var d=await json('/staff/profiles/'+encodeURIComponent(state.target),{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});state.profile=d.profile;dialog.close();render();Portal.showNotice(state.target==='me'?'Profile updated.':'Staff profile updated.')}catch(err){Portal.showNotice(err.message||'Could not save profile.','warning')}finally{button.disabled=false}}
async function load(target){Portal.clearNotice();state.target=target||'me';var d=await json('/staff/profiles/'+encodeURIComponent(state.target));state.profile=d.profile;state.editable=d.editableFields||[];state.owner=!!d.owner;render()}
async function loadDirectory(){if(!state.owner)return;var actor=Portal.getStaff&&Portal.getStaff(),tools=document.getElementById('directorProfileTools'),select=document.getElementById('directorStaffSelect');try{var d=await json('/staff/team');state.directory=d.staff||[];select.innerHTML='<option value="me">My profile</option>'+state.directory.filter(function(s){return !actor||String(s.staffId).toLowerCase()!==String(actor.staffId).toLowerCase()}).map(function(s){return '<option value="'+esc(s.staffId)+'">'+esc(s.name||s.staffId)+' · '+esc(s.role||'Staff')+'</option>'}).join('');tools.hidden=false}catch(err){Portal.showNotice('Director profile editing is available, but the staff directory could not be loaded. '+(err.message||''),'warning')}}
document.getElementById('editProfile').addEventListener('click',openEdit);document.getElementById('closeProfileDialog').addEventListener('click',function(){dialog.close()});document.getElementById('cancelProfile').addEventListener('click',function(){dialog.close()});document.getElementById('profileForm').addEventListener('submit',save);document.getElementById('directorStaffSelect').addEventListener('change',function(e){var target=e.target.value||'me';load(target).catch(function(err){Portal.showNotice(err.message||'Profile could not be loaded.','warning')})});Portal.onReady(function(){load('me').then(loadDirectory).catch(function(err){Portal.showNotice(err.message||'Profile could not be loaded.','warning')})});
})(window,document);
