/* Bodibe Digital — Sales Workspace */
(function(window,document){
  'use strict';
  var Portal=window.BodibePortal;if(!Portal)return;
  var state={data:null,followFilter:'all',leadId:'',saving:false};
  var dialog=document.getElementById('activityDialog');
  var historyDialog=document.getElementById('historyDialog');
  var MIN_ACTIVITY_NOTE_LENGTH=10;
  function el(id){return document.getElementById(id)}
  function esc(v){return Portal.escapeHtml(v==null?'':v)}
  function key(v){return String(v==null?'':v).trim().toLowerCase()}
  function money(v){return new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR',maximumFractionDigits:2}).format(Number(v)||0)}
  function date(v){if(!v)return '—';var d=new Date(String(v).length===10?v+'T12:00:00':v);return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat('en-ZA',{timeZone:'Africa/Johannesburg',day:'2-digit',month:'short',year:'numeric'}).format(d)}
  function when(v){if(!v)return '—';var d=new Date(v);return Number.isNaN(d.getTime())?String(v):new Intl.DateTimeFormat('en-ZA',{timeZone:'Africa/Johannesburg',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(d)}
  function phoneDigits(v){return String(v||'').replace(/\D/g,'')}
  function telHref(v){return 'tel:'+phoneDigits(v)}
  function waHref(v){var d=phoneDigits(v);if(d.charAt(0)==='0')d='27'+d.slice(1);return 'https://wa.me/'+d}
  async function json(path,options){var res=await Portal.authedFetch(path,options||{}),data=await res.json().catch(function(){return{}});if(!res.ok||!data.success)throw new Error(data.message||'Sales request failed.');return data}
  function leadById(id){return (state.data&&state.data.myLeads||[]).find(function(l){return key(l.leadId)===key(id)})}
  function isClosed(lead){return ['won','lost','paid'].includes(key(lead&&lead.status))}

  function renderKpis(){var d=state.data||{},k=d.kpis||{},f=d.followUps||[];el('kpiLeads').textContent=k.myLeads||0;el('kpiFollowUps').textContent=f.filter(function(x){return ['overdue','today'].includes(key(x.followUp))}).length;el('kpiQuoted').textContent=k.quoted||0;el('kpiWon').textContent=k.won||0;el('kpiConversion').textContent=(Number(k.conversionRate)||0).toFixed(1).replace('.0','')+'% conversion';el('kpiActivities').textContent=k.activities||0;el('kpiCommission').textContent=money(d.commission&&d.commission.estimatedTotal)}

  function renderFunnel(){var leads=state.data&&state.data.myLeads||[],stages=[['New','New'],['Contacted','Contacted'],['Quoted','Quoted'],['Won','Won / Paid'],['Lost','Lost']],counts=stages.map(function(s){return leads.filter(function(l){var x=key(l.status);return s[0]==='Won'?['won','paid'].includes(x):x===key(s[0])}).length}),max=Math.max.apply(Math,[1].concat(counts));el('salesFunnel').innerHTML=stages.map(function(s,i){var pct=Math.round(counts[i]/max*100);return '<div class="sales-stage"><div class="sales-stage-top"><span>'+esc(s[1])+'</span><strong>'+counts[i]+'</strong></div><div class="sales-stage-bar"><i style="width:'+pct+'%"></i></div></div>'}).join('')}

  function renderMix(){var k=state.data&&state.data.kpis||{},rows=[['Calls',k.calls||0],['WhatsApp',k.whatsapps||0],['Email',k.emails||0],['All activity',k.activities||0]],max=Math.max.apply(Math,[1].concat(rows.map(function(r){return r[1]})));el('activityMix').innerHTML=rows.map(function(r){return '<div class="sales-mix-row"><span>'+esc(r[0])+'</span><div class="sales-mix-track"><i style="width:'+Math.round(r[1]/max*100)+'%"></i></div><strong>'+r[1]+'</strong></div>'}).join('')}

  function contactLinks(l){var links=[];if(l.phone){links.push('<a class="sales-contact-chip" href="'+esc(telHref(l.phone))+'" title="Call '+esc(l.phone)+'"><i class="fa-solid fa-phone"></i><span>'+esc(l.phone)+'</span></a>');links.push('<a class="sales-contact-chip is-whatsapp" href="'+esc(waHref(l.phone))+'" target="_blank" rel="noopener" title="Open WhatsApp"><i class="fa-brands fa-whatsapp"></i><span>WhatsApp</span></a>')}if(l.email){links.push('<a class="sales-contact-chip" href="mailto:'+esc(l.email)+'" title="Email '+esc(l.email)+'"><i class="fa-solid fa-envelope"></i><span>'+esc(l.email)+'</span></a>')}return links.length?links.join(''):'<span class="sales-muted">No contact details</span>'}

  function renderMyLeads(){var rows=(state.data&&state.data.myLeads||[]).slice().sort(function(a,b){var ac=isClosed(a)?1:0,bc=isClosed(b)?1:0;if(ac!==bc)return ac-bc;return String(b.leadId||'').localeCompare(String(a.leadId||''))});var count=el('myLeadCount'),body=el('myLeadRows');if(count)count.textContent=rows.length+' '+(rows.length===1?'lead':'leads');if(!body)return;body.innerHTML=rows.length?rows.map(function(l){var last=l.lastActivity||{},follow=l.followUpDate?'<span class="sales-follow-pill is-'+esc(key(l.followUp)||'upcoming')+'">'+esc(date(l.followUpDate))+'</span>':'<span class="sales-muted">Not set</span>';return '<tr class="'+(isClosed(l)?'is-closed':'')+'"><td><span class="sales-primary">'+esc(l.clientName||'Unknown contact')+'</span><span class="sales-muted">'+esc(l.leadId)+'</span></td><td><span class="sales-primary">'+esc(l.businessName||'—')+'</span><span class="sales-muted">'+esc(l.projectType||l.selectedPackage||'')+'</span></td><td><span class="sales-stage-pill">'+esc(l.status||'New')+'</span></td><td><div class="sales-contact-stack">'+contactLinks(l)+'</div></td><td><span class="sales-primary">'+esc(last.type||'No contact yet')+'</span><span class="sales-muted">'+esc(last.outcome||'')+(last.at?' · '+esc(when(last.at)):'')+'</span></td><td>'+follow+'</td><td><div class="sales-row-actions sales-owned-actions"><button class="sales-icon-btn is-primary" data-log="'+esc(l.leadId)+'" data-type="Call"><i class="fa-solid fa-pen-to-square"></i> Log contact</button><button class="sales-icon-btn" data-history="'+esc(l.leadId)+'"><i class="fa-solid fa-clock-rotate-left"></i> History</button></div></td></tr>'}).join(''):'<tr><td colspan="7" class="sales-empty">No claimed or assigned leads yet. Claim a lead from the pool and it will appear here immediately.</td></tr>'}

  function renderFollowUps(){var all=state.data&&state.data.followUps||[],counts={all:all.length,overdue:0,today:0,upcoming:0};all.forEach(function(l){var f=key(l.followUp);if(counts[f]!==undefined)counts[f]++});el('followAllCount').textContent=counts.all;el('followOverdueCount').textContent=counts.overdue;el('followTodayCount').textContent=counts.today;el('followUpcomingCount').textContent=counts.upcoming;var rows=state.followFilter==='all'?all:all.filter(function(l){return key(l.followUp)===state.followFilter});el('followupRows').innerHTML=rows.length?rows.map(function(l){var last=l.lastActivity||{};return '<tr><td><span class="sales-primary">'+esc(l.clientName||'Unnamed contact')+'</span><span class="sales-muted">'+esc(l.leadId)+'</span></td><td>'+esc(l.businessName||'—')+'</td><td><span class="sales-stage-pill">'+esc(l.status||'New')+'</span></td><td><span class="sales-follow-pill is-'+esc(key(l.followUp)||'upcoming')+'">'+esc(date(l.followUpDate))+'</span></td><td><span class="sales-primary">'+esc(last.type||'No activity yet')+'</span><span class="sales-muted">'+esc(last.outcome||'')+(last.at?' · '+esc(when(last.at)):'')+'</span></td><td><div class="sales-row-actions"><button class="sales-icon-btn is-primary" data-log="'+esc(l.leadId)+'" data-type="Follow-Up"><i class="fa-solid fa-phone"></i> Log follow-up</button><button class="sales-icon-btn" data-history="'+esc(l.leadId)+'"><i class="fa-solid fa-clock-rotate-left"></i> History</button></div></td></tr>'}).join(''):'<tr><td colspan="6" class="sales-empty">No follow-ups in this view.</td></tr>'}

  function activityIcon(type){var map={call:'fa-phone',whatsapp:'fa-brands fa-whatsapp',email:'fa-envelope',meeting:'fa-handshake',note:'fa-note-sticky','follow-up':'fa-clock-rotate-left','correction note':'fa-pen'};return map[key(type)]||'fa-circle-dot'}
  function activityRows(rows,emptyText){return rows.length?rows.map(function(a){return '<div class="sales-timeline-item"><span class="sales-timeline-icon"><i class="fa-solid '+activityIcon(a.type)+'"></i></span><div><strong>'+esc(a.type||'Activity')+(a.businessName||a.clientName||a.leadId?' · '+esc(a.businessName||a.clientName||a.leadId):'')+'</strong><p>'+esc(a.outcome||'')+(a.note?' — '+esc(a.note):'')+(a.followUpDate?' · Next: '+esc(date(a.followUpDate)):'')+'</p><span class="sales-history-staff">'+esc(a.staffName||a.staffId||'')+'</span></div><time>'+esc(when(a.at))+'</time></div>'}).join(''):'<p class="sales-empty">'+esc(emptyText||'No sales activity has been logged yet.')+'</p>'}
  function renderActivity(){var rows=state.data&&state.data.recentActivity||[];el('activityCount').textContent=rows.length+' '+(rows.length===1?'entry':'entries');el('recentActivity').innerHTML=activityRows(rows,'No sales activity has been logged yet.')}

  function renderPool(){var rows=state.data&&state.data.unassignedLeads||[],canClaim=!!(state.data&&state.data.canClaim),card=el('availablePoolCard');if(!rows.length){el('leadPool').innerHTML='<p class="sales-empty">No leads are currently available to claim.</p>';return}el('leadPool').innerHTML=rows.slice(0,8).map(function(l){return '<div class="sales-pool-item"><div><strong>'+esc(l.businessName||l.leadId)+'</strong><span>'+esc(l.projectType||l.selectedPackage||'Unspecified service')+' · '+esc(l.status||'New')+'</span></div>'+(canClaim?'<button class="sales-claim" data-claim="'+esc(l.leadId)+'">Claim</button>':'')+'</div>'}).join('');if(card)card.hidden=false}

  function render(){renderKpis();renderFunnel();renderMix();renderMyLeads();renderFollowUps();renderActivity();renderPool();document.querySelectorAll('#followupTabs button').forEach(function(b){b.classList.toggle('is-active',b.dataset.filter===state.followFilter)})}

  function populateDialogLists(){var d=state.data||{};el('activityType').innerHTML=(d.activityTypes||[]).map(function(x){return '<option>'+esc(x)+'</option>'}).join('');el('activityOutcome').innerHTML=(d.outcomes||[]).map(function(x){return '<option>'+esc(x)+'</option>'}).join('')}
  function openActivity(id,type){var lead=leadById(id);if(!lead)return;state.leadId=id;populateDialogLists();el('activityDialogTitle').textContent=type==='Follow-Up'?'Complete follow-up':'Log contact';el('activityLeadLabel').textContent=[lead.clientName,lead.businessName,lead.leadId].filter(Boolean).join(' · ');el('activityType').value=type||'Call';el('activityOutcome').value='Follow-up';el('activityStatus').value='';el('activityFollowUp').value=lead.followUpDate||'';el('activityNote').value='';dialog.showModal()}
  function openHistory(id){var lead=leadById(id);if(!lead||!historyDialog)return;el('historyDialogTitle').textContent=lead.businessName||lead.clientName||'Conversation history';el('historyLeadLabel').textContent=[lead.clientName,lead.leadId].filter(Boolean).join(' · ');el('historyTimeline').innerHTML=activityRows(lead.activities||[],'No contact has been logged for this lead yet. Use Log contact after the first call, WhatsApp, email or meeting.');historyDialog.showModal()}
  async function saveActivity(e){e.preventDefault();if(state.saving)return;var note=el('activityNote').value.trim();if(note.length<MIN_ACTIVITY_NOTE_LENGTH){el('activityNote').focus();return Portal.showNotice('Notes are required. Add at least '+MIN_ACTIVITY_NOTE_LENGTH+' characters explaining what happened.','warning')}state.saving=true;var button=el('saveActivity');button.disabled=true;try{var payload={type:el('activityType').value,outcome:el('activityOutcome').value,note:note,followUpDate:el('activityFollowUp').value,status:el('activityStatus').value};if(!payload.status)delete payload.status;await json('/staff/sales/leads/'+encodeURIComponent(state.leadId)+'/activity',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});dialog.close();Portal.showNotice('Contact activity saved to this lead.');await load()}catch(err){Portal.showNotice(err.message||'Could not save contact activity.','warning')}finally{state.saving=false;button.disabled=false}}
  async function claim(id,button){button.disabled=true;try{await json('/staff/sales/leads/'+encodeURIComponent(id)+'/claim',{method:'POST'});Portal.showNotice('Lead claimed. It is now in My leads & contact log.');await load();var section=el('my-leads');if(section)section.scrollIntoView({behavior:'smooth',block:'start'})}catch(err){Portal.showNotice(err.message||'Could not claim that lead.','warning');button.disabled=false}}
  async function load(){var button=el('refreshSales');button.disabled=true;try{Portal.clearNotice();state.data=await json('/staff/sales-workspace');render();if(state.data.warnings&&state.data.warnings.length)Portal.showNotice(state.data.warnings.join(' '),'warning')}finally{button.disabled=false}}

  el('refreshSales').addEventListener('click',function(){load().catch(function(err){Portal.showNotice(err.message||'Could not refresh sales.','warning')})});
  el('followupTabs').addEventListener('click',function(e){var b=e.target.closest('button[data-filter]');if(!b)return;state.followFilter=b.dataset.filter;renderFollowUps();document.querySelectorAll('#followupTabs button').forEach(function(x){x.classList.toggle('is-active',x===b)})});
  document.addEventListener('click',function(e){var log=e.target.closest('[data-log]');if(log)return openActivity(log.dataset.log,log.dataset.type||'Call');var history=e.target.closest('[data-history]');if(history)return openHistory(history.dataset.history);var c=e.target.closest('[data-claim]');if(c)return claim(c.dataset.claim,c)});
  el('closeActivityDialog').addEventListener('click',function(){dialog.close()});el('cancelActivity').addEventListener('click',function(){dialog.close()});el('activityForm').addEventListener('submit',saveActivity);
  if(el('closeHistoryDialog'))el('closeHistoryDialog').addEventListener('click',function(){historyDialog.close()});
  if(el('doneHistory'))el('doneHistory').addEventListener('click',function(){historyDialog.close()});
  Portal.onReady(function(){load().catch(function(err){Portal.showNotice(err.message||'Sales Workspace could not be loaded.','warning')})});
})(window,document);