/* Bodibe Digital — Quotes workspace */
(function(window,document){'use strict';var Portal=window.BodibePortal;if(!Portal)return;var state={quotes:[],counts:{},selected:null};var list=document.getElementById('quoteList'),count=document.getElementById('quoteCount'),search=document.getElementById('quoteSearch'),status=document.getElementById('quoteStatus'),validity=document.getElementById('quoteValidity'),clear=document.getElementById('quoteClear'),drawer=document.getElementById('quoteDrawer'),backdrop=document.getElementById('quoteBackdrop');
function esc(v){return Portal.escapeHtml(v==null?'':v)}function key(v){return String(v||'').trim().toLowerCase()}function money(v){var n=Number(v||0);return new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format(isFinite(n)?n:0)}function date(v){if(!v)return'—';var d=new Date(String(v).length===10?v+'T00:00:00':v);return isNaN(d)?String(v):d.toLocaleDateString('en-ZA',{day:'numeric',month:'short',year:'numeric'})}function uniq(a){return[...new Set(a.filter(Boolean))].sort()}
async function api(path,options){var r=await Portal.authedFetch(path,options||{}),d=await r.json().catch(function(){return{}});if(!r.ok||!d.success)throw new Error(d.message||'Quotation request failed.');return d}
function card(label,value,icon){return'<article class="task-summary-card"><span><i class="fa-solid '+icon+'"></i>'+esc(label)+'</span><strong>'+esc(String(value||0))+'</strong></article>'}
function renderSummary(){var c=state.counts||{};document.getElementById('quoteSummary').innerHTML=card('Total',c.total,'fa-file-invoice')+card('Draft',c.draft,'fa-pen-to-square')+card('Approved',c.approved,'fa-circle-check')+card('Issued',c.issued,'fa-paper-plane')+card('Accepted',c.accepted,'fa-handshake')}
function renderFilters(){var current=status.value;status.innerHTML='<option value="">All</option>'+uniq(state.quotes.map(function(q){return q.status})).map(function(x){return'<option>'+esc(x)+'</option>'}).join('');status.value=current}
function filtered(){var q=key(search.value);return state.quotes.filter(function(x){if(status.value&&x.status!==status.value)return false;if(validity.value==='expired'&&!x.hasExpired)return false;if(validity.value==='active'&&x.hasExpired)return false;if(!q)return true;return[x.quoteId,x.leadId,x.clientName,x.clientEmail,x.project,x.description].some(function(v){return key(v).includes(q)})})}
function pill(v,expired){var text=expired&&['Draft','Approved','Issued'].includes(v)?'Expired':(v||'—');return'<span class="quote-pill is-'+esc(key(text).replace(/\s+/g,'-'))+'">'+esc(text)+'</span>'}
function render(){var rows=filtered();clear.hidden=!(search.value||status.value||validity.value);count.textContent=rows.length+' quote'+(rows.length===1?'':'s');if(!rows.length){list.innerHTML='<div class="tasks-empty"><i class="fa-regular fa-file-lines"></i><strong>No quotes match this view.</strong><span>Change the filters or prepare a quote from a lead.</span></div>';return}list.innerHTML='<div class="quote-table-head"><span>Quote</span><span>Client</span><span>Project</span><span>Status</span><span>Total</span><span>Valid until</span></div>'+rows.map(function(x){return'<button type="button" class="quote-row" data-quote="'+esc(x.quoteId)+'"><span class="quote-main"><strong>'+esc(x.quoteId||'Quote')+'</strong><small>'+esc(x.leadId||'')+'</small></span><span class="quote-client"><strong>'+esc(x.clientName||'—')+'</strong><small>'+esc(x.clientEmail||'')+'</small></span><span class="quote-cell">'+esc(x.project||'—')+'</span><span>'+pill(x.status,x.hasExpired)+'</span><span class="quote-money">'+esc(money(x.total))+'</span><span class="quote-cell">'+esc(date(x.validUntil))+'</span></button>'}).join('');list.querySelectorAll('[data-quote]').forEach(function(b){b.addEventListener('click',function(){openQuote(b.dataset.quote)})})}
function detail(label,value){return'<div class="task-detail-item"><span>'+esc(label)+'</span><strong>'+esc(value||'—')+'</strong></div>'}
function action(name,icon,label,cls){return'<button type="button" class="quote-action '+(cls||'')+'" data-action="'+name+'"><i class="fa-solid '+icon+'"></i>'+esc(label)+'</button>'}
function actionHtml(q){var html='';if(q.status==='Draft'&&Portal.canHere('Quotations','Approve Quotes'))html+=action('approve','fa-circle-check','Approve','is-success');if(q.status==='Approved'&&Portal.canHere('Quotations','Send Quotes'))html+=action('issue','fa-paper-plane','Mark issued');if(q.status==='Issued'&&Portal.canHere('Quotations','Edit Quotes')){html+=action('accept','fa-handshake','Client accepted','is-success');html+=action('decline','fa-thumbs-down','Client declined','is-danger')}if(!['Accepted','Declined','Cancelled'].includes(q.status)&&Portal.canHere('Quotations','Delete Quotes'))html+=action('cancel','fa-ban','Cancel quote','is-danger');return html?'<div class="quote-actions">'+html+'</div>':''}
function openQuote(id){var q=state.quotes.find(function(x){return x.quoteId===id});if(!q)return;state.selected=q;document.getElementById('quoteDrawerId').textContent=q.quoteId||'';document.getElementById('quoteDrawerTitle').textContent=q.clientName||'Quote';document.getElementById('quoteDrawerBody').innerHTML='<div class="task-detail-status">'+pill(q.status,q.hasExpired)+'</div><div class="task-detail-grid">'+detail('Lead',q.leadId)+detail('Project',q.project)+detail('Client email',q.clientEmail)+detail('Date',date(q.date))+detail('Subtotal',money(q.subtotal))+detail('Discount',money(q.discount))+detail('VAT',money(q.vat))+detail('Total',money(q.total))+detail('Valid until',date(q.validUntil))+detail('Status',q.status)+'</div>'+(q.description?'<section class="task-notes"><span>Description</span><p>'+esc(q.description)+'</p></section>':'')+(q.notes?'<section class="task-notes"><span>Notes</span><p>'+esc(q.notes)+'</p></section>':'')+actionHtml(q)+'<p class="quote-help">Accepted means the client accepted the quotation. It does not by itself create an invoice, payment or project.</p>';document.getElementById('quoteDrawerBody').querySelectorAll('[data-action]').forEach(function(b){b.addEventListener('click',function(){runAction(q,b.dataset.action,b)})});backdrop.hidden=false;drawer.hidden=false;document.body.classList.add('tasks-lock-scroll')}
function close(){drawer.hidden=true;backdrop.hidden=true;document.body.classList.remove('tasks-lock-scroll');state.selected=null}
async function runAction(q,name,button){var path='/staff/quotes/'+encodeURIComponent(q.quoteId),options={method:'POST',headers:{'Content-Type':'application/json'},body:'{}'};if(name==='approve')path+='/approve';if(name==='accept')path+='/accept';if(name==='decline')path+='/decline';if(name==='issue'){var channel=window.prompt('How did you deliver the quote? (Email, WhatsApp, PDF, in person)','WhatsApp');if(channel===null)return;if(!window.confirm('Confirm that you already delivered this quote to the client yourself.'))return;path+='/issue';options.body=JSON.stringify({confirmDelivered:'yes',channel:channel})}if(name==='cancel'){if(!window.confirm('Cancel '+q.quoteId+'? The record will be kept, but its status will become Cancelled.'))return;path+='?confirm=yes';options={method:'DELETE'}}button.disabled=true;try{var d=await api(path,options);Portal.showNotice(d.message||'Quote updated.');close();await load()}catch(e){Portal.showNotice(e.message||'Could not update quote.','warning')}finally{button.disabled=false}}
async function load(){try{var d=await api('/staff/quotes');state.quotes=d.quotes||[];state.counts=d.counts||{};renderSummary();renderFilters();render()}catch(e){Portal.showNotice(e.message||'Could not load quotes.','warning');list.innerHTML='<div class="tasks-empty"><strong>Quotes could not be loaded.</strong></div>'}}
search.addEventListener('input',render);status.addEventListener('change',render);validity.addEventListener('change',render);clear.addEventListener('click',function(){search.value='';status.value='';validity.value='';render()});document.getElementById('quoteClose').addEventListener('click',close);backdrop.addEventListener('click',close);document.addEventListener('keydown',function(e){if(e.key==='Escape'&&!drawer.hidden)close()});Portal.onReady(function(){if(!Portal.can('Quotations','View Quotes')){list.innerHTML='<div class="tasks-empty"><strong>You do not have access to quotations.</strong></div>';return}load()});
})(window,document);