/* Bodibe Digital — My Clients */
(function(window,document){'use strict';var Portal=window.BodibePortal;if(!Portal)return;var state={leads:[],quotes:[],clients:[],selected:null};var list=document.getElementById('clientList'),count=document.getElementById('clientCount'),search=document.getElementById('clientSearch'),status=document.getElementById('clientStatus'),project=document.getElementById('clientProject'),clear=document.getElementById('clientClear'),drawer=document.getElementById('clientDrawer'),backdrop=document.getElementById('clientBackdrop');
function esc(v){return Portal.escapeHtml(v==null?'':v)}function key(v){return String(v||'').trim().toLowerCase()}function money(v){var n=Number(v||0);return new Intl.NumberFormat('en-ZA',{style:'currency',currency:'ZAR'}).format(isFinite(n)?n:0)}function date(v){if(!v)return'—';var d=new Date(String(v).length===10?v+'T00:00:00':v);return isNaN(d)?String(v):d.toLocaleDateString('en-ZA',{day:'numeric',month:'short',year:'numeric'})}function uniq(a){return[...new Set(a.filter(Boolean))].sort()}
async function api(path){var r=await Portal.authedFetch(path),d=await r.json().catch(function(){return{}});if(!r.ok||!d.success)throw new Error(d.message||'Could not load client data.');return d}
function acceptedQuote(leadId){return state.quotes.filter(function(q){return q.leadId===leadId&&q.status==='Accepted'}).sort(function(a,b){return String(b.date||'').localeCompare(String(a.date||''))})[0]||null}
function build(){state.clients=state.leads.filter(function(l){return['won','paid','awaiting payment'].includes(key(l.status))||!!acceptedQuote(l.leadId)}).map(function(l){var q=acceptedQuote(l.leadId);return{lead:l,quote:q,status:q?'Accepted':l.status||'Client',project:l.projectType||l.selectedPackage||q&&q.project||'—',total:q&&q.total||0}})}
function card(label,value,icon){return'<article class="task-summary-card"><span><i class="fa-solid '+icon+'"></i>'+esc(label)+'</span><strong>'+esc(String(value))+'</strong></article>'}
function renderSummary(){var total=state.clients.length,accepted=state.clients.filter(function(c){return c.quote}).length,awaiting=state.clients.filter(function(c){return key(c.lead.status)==='awaiting payment'}).length,follow=state.clients.filter(function(c){return['today','overdue'].includes(key(c.lead.followUp))}).length;document.getElementById('clientSummary').innerHTML=card('Clients',total,'fa-user-group')+card('Accepted quotes',accepted,'fa-file-circle-check')+card('Awaiting payment',awaiting,'fa-hourglass-half')+card('Follow-ups due',follow,'fa-clock')}
function renderFilters(){var s=status.value,p=project.value;status.innerHTML='<option value="">All</option>'+uniq(state.clients.map(function(c){return c.status})).map(function(x){return'<option>'+esc(x)+'</option>'}).join('');project.innerHTML='<option value="">All</option>'+uniq(state.clients.map(function(c){return c.project})).map(function(x){return'<option>'+esc(x)+'</option>'}).join('');status.value=s;project.value=p}
function filtered(){var q=key(search.value);return state.clients.filter(function(c){if(status.value&&c.status!==status.value)return false;if(project.value&&c.project!==project.value)return false;if(!q)return true;var l=c.lead;return[l.clientName,l.businessName,l.email,l.phone,c.project,l.leadId].some(function(v){return key(v).includes(q)})})}
function pill(v){var k=key(v).replace(/\s+/g,'-');return'<span class="client-pill is-'+esc(k)+'">'+esc(v||'Client')+'</span>'}
function render(){var rows=filtered();clear.hidden=!(search.value||status.value||project.value);count.textContent=rows.length+' client'+(rows.length===1?'':'s');if(!rows.length){list.innerHTML='<div class="clients-empty">No clients match this view.</div>';return}list.innerHTML='<div class="client-table-head"><span>Client</span><span>Business</span><span>Service</span><span>Status</span><span>Quote value</span><span>Follow-up</span></div>'+rows.map(function(c){var l=c.lead;return'<button class="client-row" type="button" data-client="'+esc(l.leadId)+'"><span class="client-primary"><strong>'+esc(l.clientName||'Unnamed client')+'</strong><small>'+esc(l.email||l.leadId)+'</small></span><span class="client-business"><strong>'+esc(l.businessName||'—')+'</strong><small>'+esc(l.phone||'')+'</small></span><span class="client-cell">'+esc(c.project)+'</span><span>'+pill(c.status)+'</span><span class="client-money">'+(c.total?esc(money(c.total)):'—')+'</span><span class="client-cell">'+esc(date(l.followUpDate))+'</span></button>'}).join('');list.querySelectorAll('[data-client]').forEach(function(b){b.addEventListener('click',function(){openClient(b.dataset.client)})})}
function detail(label,value){return'<div class="task-detail-item"><span>'+esc(label)+'</span><strong>'+esc(value||'—')+'</strong></div>'}
function openClient(id){var c=state.clients.find(function(x){return x.lead.leadId===id});if(!c)return;state.selected=c;var l=c.lead,q=c.quote;document.getElementById('clientDrawerId').textContent=l.leadId;document.getElementById('clientDrawerTitle').textContent=l.clientName||'Client';document.getElementById('clientDrawerBody').innerHTML='<div class="task-detail-status">'+pill(c.status)+'</div><div class="task-detail-grid">'+detail('Business',l.businessName)+detail('Service',c.project)+detail('Email',l.email)+detail('Phone',l.phone)+detail('Follow-up',date(l.followUpDate))+detail('Quote',q&&q.quoteId)+detail('Quote value',q?money(q.total):'—')+detail('Lead status',l.status)+'</div>'+(l.notes?'<section class="task-notes"><span>CRM notes</span><p>'+esc(l.notes)+'</p></section>':'')+'<div class="client-contact-links">'+(l.phone?'<a href="tel:'+esc(String(l.phone).replace(/\s+/g,''))+'"><i class="fa-solid fa-phone"></i>Call</a>':'')+(l.email?'<a href="mailto:'+esc(l.email)+'"><i class="fa-solid fa-envelope"></i>Email</a>':'')+'</div><a class="tasks-create client-open-lead" href="staff-leads.html"><i class="fa-solid fa-arrow-up-right-from-square"></i>Open CRM</a>';backdrop.hidden=false;drawer.hidden=false;document.body.classList.add('tasks-lock-scroll')}
function close(){drawer.hidden=true;backdrop.hidden=true;document.body.classList.remove('tasks-lock-scroll');state.selected=null}
async function load(){try{var leads=await api('/staff/leads');state.leads=leads.leads||[];try{var quotes=await api('/staff/quotes');state.quotes=quotes.quotes||[]}catch(e){state.quotes=[]}build();renderSummary();renderFilters();render()}catch(e){Portal.showNotice(e.message||'Could not load clients.','warning');list.innerHTML='<div class="clients-empty">Clients could not be loaded.</div>'}}
search.addEventListener('input',render);status.addEventListener('change',render);project.addEventListener('change',render);clear.addEventListener('click',function(){search.value='';status.value='';project.value='';render()});document.getElementById('clientClose').addEventListener('click',close);backdrop.addEventListener('click',close);document.addEventListener('keydown',function(e){if(e.key==='Escape'&&!drawer.hidden)close()});Portal.onReady(load);
})(window,document);